### PR TITLE
remove Python2 support

### PR DESCRIPTION
**Pull request by a-detiste**
we are trying to slowly remove six from distributions

### CODE REVIEW

**Comment by shlomif** [comment]
@a-detiste : merged, thanks!

**Comment by a-detiste** [comment]
Hi, should I propose the same for PySolFC ?

**Comment by shlomif** [comment]
@a-detiste : re PySol FC use of "six.py" for supporting Python 2: I'm not sure it will be recommended to remove it. This is given PySol FC is commonly deployed to MSWindows and macOS desktops.

@joeraz : what do you think?

**Comment by joeraz** [comment]
Frankly, I've been wanting to drop Python 2 support for a while.  Just never got around to asking.

I do have a Windows test environment, and I run it with Python 3 there.  Though I don't have a Mac environment, the script that generates the Mac packages also uses Python 3.  My only uncertainty was if some obscure Linux distro needed it, but there are a couple longstanding bugs when running in Python 2 that never got reported, so I don't think Python 2 support is being used.

Feel free to open an issue on the main PySolFC repo.

**Comment by shlomif** [comment]
@joeraz : thanks for your informative reply

**Pull request merged**
